const getConsultaCredito =
    (request, response) => {
        // Parsear a nova URL: /v1/vloz/credito/01/consulta?$filter=cliente eq '1006085' and data_lancamento ge 2025-02-04 and data_lancamento le 2025-02-04

        const url = request.url;

        // Extrair o query string e decodificar
        const queryString = url.split('?')[1];
        if (!queryString) {
            return response.status(400).json({ error: 'Query string não encontrada' });
        }

        // Decodificar a query string (URL-encoded)
        const decodedQuery = decodeURIComponent(queryString);

        // Extrair parâmetros do $filter usando regex
        const clienteMatch = decodedQuery.match(/cliente\s+eq\s+'([^']+)'/);
        const dataGeMatch = decodedQuery.match(/data_lancamento\s+ge\s+([^\s&]+)/);
        const dataLeMatch = decodedQuery.match(/data_lancamento\s+le\s+([^\s&]+)/);

        if (!clienteMatch) {
            return response.status(400).json({ error: 'Formato de URL inválido - cliente não encontrado' });
        }

        const cliente = clienteMatch[1];
        const dataInicio = dataGeMatch ? dataGeMatch[1] : null;
        const dataFim = dataLeMatch ? dataLeMatch[1] : null;

        //console.log(`Consulta Crédito - Cliente: ${cliente}, Data Início: ${dataInicio}, Data Fim: ${dataFim}`);

        const now = new Date();
        const timestamp = now.getFullYear().toString() +
            (now.getMonth() + 1).toString().padStart(2, '0') +
            now.getDate().toString().padStart(2, '0') +
            now.getHours().toString().padStart(2, '0') +
            now.getMinutes().toString().padStart(2, '0') +
            now.getSeconds().toString().padStart(2, '0');

        const jsonResponse = {
            "@odata.context": `../$metadata#consulta`,
            "@odata.metadataEtag": `W/"datetime'${timestamp}'"`,
            "value": [
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "5000266868",
                    "cliente": "1006085",
                    "cod_raz_especial": "7",
                    "num_atribuicao": "Vloz",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "VLOZ",
                    "tipo_doc": "AB",
                    "divisao": "4001",
                    "valor": 1278.00,
                    "contab_geral": "21601012",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "2044667522",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "",
                    "credito_debito": "H",
                    "codigo_razao": ""
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "1100003730",
                    "cliente": "1006085",
                    "cod_raz_especial": "",
                    "num_atribuicao": "",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "UTIL. CRED.",
                    "tipo_doc": "CL",
                    "divisao": "4070",
                    "valor": 574.83,
                    "contab_geral": "11201010",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "UTIL. CRED.",
                    "credito_debito": "S",
                    "codigo_razao": ""
                },
                {
                    "empresa": "4014",
                    "adquirente": "01",
                    "exercicio": "2025",
                    "doc_contab": "1300078059",
                    "cliente": "1006085",
                    "cod_raz_especial": "7",
                    "num_atribuicao": "VLOZ-Crédito",
                    "data_lancamento": "2025-02-03",
                    "data_doc": "2025-02-03",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "VLOZ-CRÉDITO",
                    "tipo_doc": "DZ",
                    "divisao": "4001",
                    "valor": 2107.44,
                    "contab_geral": "21601012",
                    "dta_calc_venc": "2025-02-03",
                    "forma_pag_financ": "",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "",
                    "area_credito": "4014",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "VLOZ-Crédito",
                    "credito_debito": "H",
                    "codigo_razao": "A"
                },
                {
                    "empresa": "4014",
                    "adquirente": "01",
                    "exercicio": "2025",
                    "doc_contab": "1300080891",
                    "cliente": "1006085",
                    "cod_raz_especial": "7",
                    "num_atribuicao": "VLOZ-Crédito",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "VLOZ-CRÉDITO",
                    "tipo_doc": "DZ",
                    "divisao": "4001",
                    "valor": 2963.98,
                    "contab_geral": "21601012",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "",
                    "area_credito": "4014",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "VLOZ-Crédito",
                    "credito_debito": "H",
                    "codigo_razao": "A"
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "1400135161",
                    "cliente": "1006085",
                    "cod_raz_especial": "R",
                    "num_atribuicao": "",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "",
                    "tipo_doc": "LC",
                    "divisao": "4001",
                    "valor": 113.67,
                    "contab_geral": "11201010",
                    "dta_calc_venc": "2025-03-18",
                    "forma_pag_financ": "F",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "Cobrança bancária UNIVALE UN Como ref.",
                    "credito_debito": "S",
                    "codigo_razao": "W"
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "2000222947",
                    "cliente": "1006085",
                    "cod_raz_especial": "",
                    "num_atribuicao": "9058131252",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "002600912-6",
                    "tipo_doc": "RV",
                    "divisao": "4002",
                    "valor": 13902.00,
                    "contab_geral": "11201010",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "F",
                    "forma_pag_pedido": "within 7 days Due net",
                    "doc_faturamento": "9058131252",
                    "doc_vendas": "2046730352",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 13902.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 13902.00,
                    "valor_pedido_nf": 13902.00,
                    "valor_pedido_ov": 13902.00,
                    "text": "3931730 - Vínculo - Compensação de Crédito",
                    "credito_debito": "S",
                    "codigo_razao": ""
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "2000222948",
                    "cliente": "1006085",
                    "cod_raz_especial": "",
                    "num_atribuicao": "9058131253",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "002600913-6",
                    "tipo_doc": "RV",
                    "divisao": "4002",
                    "valor": 113.67,
                    "contab_geral": "11201010",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "F",
                    "forma_pag_pedido": "within 42 days Due net",
                    "doc_faturamento": "9058131253",
                    "doc_vendas": "2046730352",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 113.67,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 113.67,
                    "valor_pedido_nf": 113.67,
                    "valor_pedido_ov": 113.67,
                    "text": "Doc. Faturamento UNIVALE UN Como ref.",
                    "credito_debito": "S",
                    "codigo_razao": ""
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "2000222950",
                    "cliente": "1006085",
                    "cod_raz_especial": "",
                    "num_atribuicao": "9058131255",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "002600914-6",
                    "tipo_doc": "RV",
                    "divisao": "4002",
                    "valor": 835.00,
                    "contab_geral": "11201010",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "F",
                    "forma_pag_pedido": "within 28 days Due net",
                    "doc_faturamento": "9058131255",
                    "doc_vendas": "2046730352",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 835.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 835.00,
                    "valor_pedido_nf": 835.00,
                    "valor_pedido_ov": 835.00,
                    "text": "3931737 - Vínculo - Compensação de Crédito",
                    "credito_debito": "S",
                    "codigo_razao": ""
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "5000265487",
                    "cliente": "1006085",
                    "cod_raz_especial": "7",
                    "num_atribuicao": "CASHBACK VLOZ",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "CASHBACK VLOZ",
                    "tipo_doc": "AB",
                    "divisao": "4001",
                    "valor": 1823.87,
                    "contab_geral": "21601012",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "CASHBACK VLOZ  JANEIRO",
                    "credito_debito": "H",
                    "codigo_razao": "A"
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "5000266707",
                    "cliente": "1006085",
                    "cod_raz_especial": "",
                    "num_atribuicao": "",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "VLOZ",
                    "tipo_doc": "AB",
                    "divisao": "4002",
                    "valor": 835.00,
                    "contab_geral": "11201010",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "Documento contábil UNIVALE UN Como ref.",
                    "credito_debito": "H",
                    "codigo_razao": ""
                },
                {
                    "empresa": "4014",
                    "adquirente": "",
                    "exercicio": "2025",
                    "doc_contab": "5000266868",
                    "cliente": "1006085",
                    "cod_raz_especial": "",
                    "num_atribuicao": "",
                    "data_lancamento": "2025-02-04",
                    "data_doc": "2025-02-04",
                    "codigo_moeda": "BRL",
                    "num_doc_ref": "VLOZ",
                    "tipo_doc": "AB",
                    "divisao": "4002",
                    "valor": 13902.00,
                    "contab_geral": "11201010",
                    "dta_calc_venc": "2025-02-04",
                    "forma_pag_financ": "",
                    "forma_pag_pedido": "",
                    "doc_faturamento": "",
                    "doc_vendas": "",
                    "area_credito": "4000",
                    "total_nf_c_desconto": 0.00,
                    "saldo_vloz_usado": 0.00,
                    "valor_boletos": 0.00,
                    "valor_pedido_nf": 0.00,
                    "valor_pedido_ov": 0.00,
                    "text": "Documento contábil UNIVALE UN Como ref.",
                    "credito_debito": "H",
                    "codigo_razao": ""
                }
            ]
        };

        return response.status(200).json(jsonResponse);
    };

module.exports =
{
    getConsultaCredito
};